# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stoper.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 500)
        Form.setStyleSheet("background-color: rgb(53, 53, 53);\n"
"color: rgb(236, 236, 236);\n"
"")
        self.startButton = QtWidgets.QPushButton(Form)
        self.startButton.setGeometry(QtCore.QRect(150, 360, 100, 100))
        self.startButton.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"                border-radius: 50px;        \n"
"                color: white;               \n"
"                font-size: 20px;           \n"
"                border: 2px solid rgb(236, 236, 236);\n"
"hover{\n"
"    background-color: rgb(175, 175, 175)\n"
"}\n"
"    ")
        self.startButton.setText("")
        self.startButton.setObjectName("startButton")
        self.min = QtWidgets.QLabel(Form)
        self.min.setGeometry(QtCore.QRect(210, 120, 60, 70))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.min.setFont(font)
        self.min.setStyleSheet("background-color: transparent")
        self.min.setObjectName("min")
        self.sec = QtWidgets.QLabel(Form)
        self.sec.setGeometry(QtCore.QRect(230, 175, 40, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sec.setFont(font)
        self.sec.setStyleSheet("background-color: transparent;")
        self.sec.setObjectName("sec")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(75, 60, 250, 250))
        self.frame.setStyleSheet("background-color: transparent; \n"
"    border: 5px solid rgb(236, 236, 236);     \n"
"    border-radius: 100%;            \n"
"    min-width: 100px;\n"
"    min-height: 100px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.hour = QtWidgets.QLabel(Form)
        self.hour.setGeometry(QtCore.QRect(140, 120, 80, 70))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.hour.setFont(font)
        self.hour.setStyleSheet("background-color: transparent")
        self.hour.setObjectName("hour")
        self.frame.raise_()
        self.startButton.raise_()
        self.min.raise_()
        self.sec.raise_()
        self.hour.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.min.setText(_translate("Form", "00"))
        self.sec.setText(_translate("Form", "00"))
        self.hour.setText(_translate("Form", "00:"))
