# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(300, 300)
        Dialog.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.confirmTimer = QtWidgets.QPushButton(Dialog)
        self.confirmTimer.setGeometry(QtCore.QRect(75, 180, 150, 40))
        self.confirmTimer.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"                border-radius: 15px;        \n"
"               border: 2px solid rgb(236, 236, 236);\n"
"hover{\n"
"    background-color: rgb(175, 175, 175)\n"
"}\n"
"    ")
        self.confirmTimer.setText("")
        self.confirmTimer.setObjectName("confirmTimer")
        self.resetTimer = QtWidgets.QPushButton(Dialog)
        self.resetTimer.setGeometry(QtCore.QRect(75, 240, 150, 40))
        self.resetTimer.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"                border-radius: 15px;        \n"
"               border: 2px solid rgb(236, 236, 236);\n"
"hover{\n"
"    background-color: rgb(175, 175, 175)\n"
"}\n"
"    ")
        self.resetTimer.setText("")
        self.resetTimer.setObjectName("resetTimer")
        self.time = QtWidgets.QLabel(Dialog)
        self.time.setGeometry(QtCore.QRect(35, 30, 230, 75))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.time.setFont(font)
        self.time.setStyleSheet("color: white;\n"
"text-align: center;\n"
" border-radius: 15px;\n"
"")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.plusHalf = QtWidgets.QPushButton(Dialog)
        self.plusHalf.setGeometry(QtCore.QRect(40, 110, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plusHalf.setFont(font)
        self.plusHalf.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"                border-radius: 15px;        \n"
"               border: 2px solid rgb(236, 236, 236);\n"
"color: rgb(53, 53, 53)")
        self.plusHalf.setObjectName("plusHalf")
        self.plusOne = QtWidgets.QPushButton(Dialog)
        self.plusOne.setGeometry(QtCore.QRect(120, 110, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plusOne.setFont(font)
        self.plusOne.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"                border-radius: 15px;        \n"
"               border: 2px solid rgb(236, 236, 236);\n"
"color: rgb(53, 53, 53)")
        self.plusOne.setObjectName("plusOne")
        self.plusFive = QtWidgets.QPushButton(Dialog)
        self.plusFive.setGeometry(QtCore.QRect(200, 110, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plusFive.setFont(font)
        self.plusFive.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"                border-radius: 15px;        \n"
"               border: 2px solid rgb(236, 236, 236);\n"
"color: rgb(53, 53, 53)")
        self.plusFive.setObjectName("plusFive")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(25, 25, 250, 125))
        self.frame.setStyleSheet("border: 2px solid white;\n"
"border-radius: 30px;\n"
"background-color: transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.confirmTimer.raise_()
        self.resetTimer.raise_()
        self.time.raise_()
        self.plusHalf.raise_()
        self.plusOne.raise_()
        self.plusFive.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.time.setText(_translate("Dialog", "00:00:00"))
        self.plusHalf.setText(_translate("Dialog", "+0:30"))
        self.plusOne.setText(_translate("Dialog", "+1:00"))
        self.plusFive.setText(_translate("Dialog", "+5:00"))
