# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(300, 300)
        Dialog.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.confirmAlarm = QtWidgets.QPushButton(Dialog)
        self.confirmAlarm.setGeometry(QtCore.QRect(75, 180, 150, 40))
        self.confirmAlarm.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"                border-radius: 15px;        \n"
"               border: 2px solid rgb(236, 236, 236);\n"
"hover{\n"
"    background-color: rgb(175, 175, 175)\n"
"}\n"
"    ")
        self.confirmAlarm.setText("")
        self.confirmAlarm.setObjectName("confirmAlarm")
        self.resetAlarm = QtWidgets.QPushButton(Dialog)
        self.resetAlarm.setGeometry(QtCore.QRect(75, 240, 150, 40))
        self.resetAlarm.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"                border-radius: 15px;        \n"
"               border: 2px solid rgb(236, 236, 236);\n"
"hover{\n"
"    background-color: rgb(175, 175, 175)\n"
"}\n"
"    ")
        self.resetAlarm.setText("")
        self.resetAlarm.setObjectName("resetAlarm")
        self.alarmValue = QtWidgets.QLineEdit(Dialog)
        self.alarmValue.setGeometry(QtCore.QRect(25, 30, 250, 125))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.alarmValue.setFont(font)
        self.alarmValue.setStyleSheet("color: white;\n"
"border: 2px solid white;\n"
"border-radius: 30px;")
        self.alarmValue.setAlignment(QtCore.Qt.AlignCenter)
        self.alarmValue.setObjectName("alarmValue")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.alarmValue.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">00:00:00</span></p></body></html>"))
